steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['psuh', 'gcr.io/$PROJECT_ID/${_APP_NAME}:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'latest-workflow', '--image', 'gcr.io/$PROJECT_ID/${_APP_NAME}:latest', '--platform', 'managed', '--region', '${_REGION}']
- name: 'maven:3-jdk-8'
  entrypoint: mvn
  args: ['test']
- name: 'maven:3-jdk-8'
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'uatbeta-workflow', '--image', 'gcr.io/$PROJECT_ID/${_APP_NAME}:latest', '--platform', 'managed', '--region', '${_REGION}']
images:
- gcr.io/$PROJECT_ID/${_APP_NAME}:latest